defaults:
  - default.yaml

gpus: 0

min_epochs: 1
max_epochs: 10

# prints
progress_bar_refresh_rate: null
weights_summary: "top"
profiler: "simple"

# debugs
num_sanity_val_steps: 0
overfit_batches: 1
limit_train_batches: 10
limit_val_batches: 0
limit_test_batches: 0
track_grad_norm: -1
terminate_on_nan: true
