
# prefix - apply Before Normalization And Resize
prefix:
  - _target_: albumentations.RandomResizedCrop
    height: ${datamodule.input_height}
    width: ${datamodule.input_width}
    scale: [0.1, 1]
    p: 0.8

# postfix - apply After Normalization And Resize
postfix:

  - _target_: albumentations.HorizontalFlip
    p: 0.5

  #OneOF
  - _target_: albumentations.OneOf
    p: 0.1
    transforms:
      - _target_: albumentations.MultiplicativeNoise
        multiplier: 0.5
        p: 1
      - _target_: albumentations.MultiplicativeNoise
        multiplier: 1.5
        p: 1
      - _target_: albumentations.MultiplicativeNoise
        multiplier: [0.5, 1.5]
        per_channel: True
        p: 1
      - _target_: albumentations.MultiplicativeNoise
        multiplier: [ 0.5, 1.5 ]
        elementwise: True
        p: 1
      - _target_: albumentations.MultiplicativeNoise
        multiplier: [ 0.5, 1.5 ]
        per_channel: True
        elementwise: True
        p: 1


  - _target_: albumentations.ImageCompression
    quality_lower: 10
    quality_upper: 60
    p: 0.005



  #OneOF
  - _target_: albumentations.OneOf
    p: 0.005
    transforms:
      - _target_: albumentations.ChannelDropout
        channel_drop_range: [1, 1]
        fill_value: 0
        p: 1
      - _target_: albumentations.ChannelShuffle
        p: 1



  #OneOF
  - _target_: albumentations.OneOf
    p: 0.05
    transforms:
      - _target_: albumentations.MotionBlur
        blur_limit: [3, 23]
        p: 1
      - _target_: albumentations.CLAHE
        clip_limit: 2
        p: 1
      - _target_: albumentations.RandomBrightnessContrast
        p: 1


  - _target_: albumentations.Rotate
    limit: 20
    p: 0.2


