# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - trainer: default
  - callbacks: default
  - model: pix2pix/base
  - datamodule: default
  - logger: null # set logger here or use command line (e.g. `python run.py logger=wandb`)

  - mode: default

  - experiment: null
  - hparams_search: null

  # enable color logging
#  - override hydra/hydra_logging: colorlog
#  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# load checkpoint weights
checkpoint: null

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: True

# upload the best model achieved during training to logging platform
# lightning chooses best model based on metric specified in checkpoint callback
upload_best_model: True

# upload all saved checkpoints during training: last, best, top k
upload_checkpoints: False

# seed for random number generators in pytorch, numpy and python.random
seed: 9

# name of the run, accessed by loggers
name: ???


#help https://github.com/facebookresearch/hydra/blob/main/examples/configure_hydra/custom_help/conf/config.yaml